### ISSUE TITLE
Inkscape 1.1.1

### ISSUE THREAD

**Issue by magdesign** [bferrarese/raster2laser_gcode#12]
It seems that every release of inkscape now breaks this plugin ;(

Just tried on Ubuntu Linux with Inkscape 1.1.1 to generate some code, which ends up in an error :
![error_inkscap_1 1 1](https://user-images.githubusercontent.com/5273166/137154217-f92db637-8814-4f20-ac4a-b5d0652d2d68.png)

**Comment by rusak47** [comment]
@magdesign 
Possibly it should be fixed in more recent version of Inkscape. See https://gitlab.com/inkscape/extensions/-/merge_requests/589, https://gitlab.com/inkscape/inkscape/-/issues/4163.
As a workaround, you may add ```os.environ["SELF_CALL"] = "true"``` into raster2laser_gcode.py at line before subprocess.Popen in exportPage method.

It worked for Inkscape 1.3 (built in july 2023)

**Comment by magdesign** [comment]
thanks.
badly, i sold everything i owned and now cycling the world (brandisbrandisbrand dot com).

 sorry but can not test your great work :)

**Comment by rusak47** [comment]
> thanks. badly, i sold everything i owned and now cycling the world (brandisbrandisbrand dot com).
> 
> sorry but can not test your great work :)

You are awesome ;) Fair winds!
